"""update_file_metadata

Revision ID: 4cced060d873
Revises: ec013735064a
Create Date: 2026-02-09 21:09:21.991892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cced060d873'
down_revision: Union[str, Sequence[str], None] = 'ec013735064a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('removed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'removed_at')
    # ### end Alembic commands ###
