"""add ip_address to file_metadata

Revision ID: ec013735064a
Revises: 2791afeca052
Create Date: 2026-02-09 19:22:42.538992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ec013735064a'
down_revision: Union[str, Sequence[str], None] = '2791afeca052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_metadata', sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_metadata', 'ip_address')
    # ### end Alembic commands ###
